version: "3"
services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
  express:
    build: ./backend
    ports:
      - "3001:3001"
  mysql:
    image: mysql:5.7
    
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: